In [1]:
import numpy as geek 
   
in_arr1 = geek.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = geek.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2)  
  

out_arr = geek.hstack((in_arr1, in_arr2)) 
print ("Output horizontally stacked array:\n ", out_arr) 

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]
