In [ ]:
Answer:-

In [1]:
import numpy as np


arr = np.random.randint(1, 101, size=(3, 3))
print("Original array:")
print(arr)


arr_transposed = arr.T
print("\nTransposed array:")
print(arr_transposed)


Original array:
[[65  9 96]
 [88 79 33]
 [75 65 88]]

Transposed array:
[[65 88 75]
 [ 9 79 65]
 [96 33 88]]


In [3]:
import numpy as np

#
arr = np.arange(1, 11)
print("Original 1D array:")
print(arr)


arr_2x5 = arr.reshape(2, 5)
print("\nReshaped into 2x5 array:")
print(arr_2x5)


arr_5x2 = arr.reshape(5, 2)
print("\nReshaped into 5x2 array:")
print(arr_5x2)


Original 1D array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped into 2x5 array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped into 5x2 array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [5]:
import numpy as np


arr = np.random.random((4, 4))
print("Original 4x4 array:")
print(arr)


arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("\nArray with border of zeros (6x6):")
print(arr_with_border)


Original 4x4 array:
[[0.68258084 0.00258397 0.18526558 0.81656826]
 [0.00339629 0.91726209 0.84463774 0.03526754]
 [0.56386678 0.80222485 0.64086624 0.57809499]
 [0.50448213 0.61183334 0.84388739 0.52346946]]

Array with border of zeros (6x6):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.68258084 0.00258397 0.18526558 0.81656826 0.        ]
 [0.         0.00339629 0.91726209 0.84463774 0.03526754 0.        ]
 [0.         0.56386678 0.80222485 0.64086624 0.57809499 0.        ]
 [0.         0.50448213 0.61183334 0.84388739 0.52346946 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [7]:
import numpy as np


arr = np.arange(10, 61, 5)
print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


In [9]:
import numpy as np


arr = np.array(['python', 'numpy', 'pandas'])


uppercase = np.char.upper(arr)
lowercase = np.char.lower(arr)
titlecase = np.char.title(arr)
capitalize = np.char.capitalize(arr)

# Print results
print("Original array:")
print(arr)

print("\nUppercase:")
print(uppercase)

print("\nLowercase:")
print(lowercase)

print("\nTitle case:")
print(titlecase)

print("\nCapitalize:")
print(capitalize)


Original array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title case:
['Python' 'Numpy' 'Pandas']

Capitalize:
['Python' 'Numpy' 'Pandas']


In [ ]:
Answer:-

In [11]:
import numpy as np

words = np.array(['python', 'numpy', 'pandas'])


words_with_spaces = np.char.add(' ', np.char.add(words, ''))
print("Original words:")
print(words)

print("\nWords with spaces between characters:")
print(words_with_spaces)


Original words:
['python' 'numpy' 'pandas']

Words with spaces between characters:
[' python' ' numpy' ' pandas']


In [ ]:
Answer:-

In [15]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])


addition = arr1 + arr2


subtraction = arr1 - arr2


multiplication = arr1 * arr2


division = np.divide(arr1, arr2)

# Print results
print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

print("\nElement-wise addition:")
print(addition)

print("\nElement-wise subtraction:")
print(subtraction)

print("\nElement-wise multiplication:")
print(multiplication)

print("\nElement-wise division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Element-wise addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Element-wise subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Element-wise division:
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [ ]:
Answer:-

In [17]:
import numpy as np

identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)


diagonal_elements = np.diagonal(identity_matrix)
print("\nDiagonal elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal elements:
[1. 1. 1. 1. 1.]


In [ ]:
Answer:-

In [23]:
import numpy as np


def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

random_numbers = np.random.randint(0, 1001, 100)

prime_numbers = [num for num in random_numbers if is_prime(num)]

print("Random numbers array:")
print(random_numbers)

print("\nPrime numbers in the array:")
print(prime_numbers)


Random numbers array:
[896 274 836  45  30 534 959  96 880 310  70 921 281 531 757 566 956   6
  82 525 378 891 373  99 979 992 965 139  72 822  35 585 968 477 808 407
 389 540  29 393 875 686 481 750 249 996 940 645 765 528 119   3 189 780
 561  43 645 161 184 701 537 400  42 425 244 870 177 977 599 949 201 268
 111 189 754 918 468 923 123 591 926 462 763 845 377 115 868 632 463 199
 603 595  25 476 853  97 483 602 209 376]

Prime numbers in the array:
[281, 757, 373, 139, 389, 29, 3, 43, 701, 977, 599, 463, 199, 853, 97]


In [ ]:
Answer:-

In [27]:
import numpy as np


daily_temperatures = np.random.randint(15, 36, 30)
print("Daily temperatures for the month:")
print(daily_temperatures)


weekly_temperatures = daily_temperatures.reshape(4, 7)


weekly_averages = np.mean(weekly_temperatures, axis=1)

print("\nWeekly averages of temperatures:")
print(weekly_averages)


Daily temperatures for the month:
[27 34 25 26 24 28 17 27 34 17 29 31 15 29 22 32 32 30 22 34 25 35 22 18
 30 29 33 32 16 20]


ValueError: cannot reshape array of size 30 into shape (4,7)